### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by EL-shadow** [JetBrains/projector-installer#2]
Readme https://github.com/JetBrains/projector-installer/blob/master/README.md contains the command `sudo apt install`
it probably must be `sudo apt-get install`?

I try this command on Ubuntu 16.04

**Comment by SerVB** [comment]
Hey! I thought there was no difference. However, I've just googled, there are some minor ones: <https://askubuntu.com/a/446484>. But I think it's just shorter to write.

So we leave it.

By the way, it's strange that issues are turned on for this repo, we have another place: <https://youtrack.jetbrains.com/issues/PRJ>. I'll close the page here.
